const std = @import("std");
const platform = @import("platform");
const ts = platform.ts;

pub fn runDoc(allocator: std.mem.Allocator, file_path: []const u8) anyerror!void {
    const source = platform.fs.cwd().readFileAlloc(allocator, file_path, 10 * 1024 * 1024) catch {
        // platform.debug.print("Error reading {s}: {}\n", .{ file_path, e });
        return;
    };
    defer allocator.free(source);

    const parser = ts.ts_parser_new() orelse return;
    defer ts.ts_parser_delete(parser);
    if (!ts.ts_parser_set_language(parser, platform.tree_sitter_heaven())) return;

    const tree = ts.ts_parser_parse_string(parser, null, source.ptr, @intCast(source.len)) orelse return;
    defer ts.ts_tree_delete(tree);

    const root = ts.ts_tree_root_node(tree);
    const count = ts.ts_node_child_count(root);

    var output = std.ArrayListUnmanaged(u8){};
    defer output.deinit(allocator);
    var w = output.writer(allocator);

    // Header
    try w.writeAll("# ");
    try w.writeAll(file_path);
    try w.writeAll("\n\nGenerated by `heaven doc`\n\n---\n\n");

    // Collect last comment before each declaration
    var last_comment: ?[]const u8 = null;
    var i: u32 = 0;

    while (i < count) : (i += 1) {
        const child = ts.ts_node_child(root, i);
        const ntype = span(ts.ts_node_type(child));

        if (std.mem.eql(u8, ntype, "comment")) {
            last_comment = nodeText(source, child);
            continue;
        }

        if (std.mem.eql(u8, ntype, "fn_decl") or std.mem.eql(u8, ntype, "dist_fn")) {
            try docFn(source, child, &w, last_comment);
        } else if (std.mem.eql(u8, ntype, "struct_decl")) {
            try docStruct(source, child, &w, last_comment);
        } else if (std.mem.eql(u8, ntype, "enum_decl")) {
            try docEnum(source, child, &w, last_comment);
        } else if (std.mem.eql(u8, ntype, "effect_decl")) {
            try docEffect(source, child, &w, last_comment);
        } else if (std.mem.eql(u8, ntype, "class_decl")) {
            try docNamed(source, child, &w, "Typeclass", last_comment);
        } else if (std.mem.eql(u8, ntype, "actor_decl")) {
            try docNamed(source, child, &w, "Actor", last_comment);
        } else if (std.mem.eql(u8, ntype, "test_decl")) {
            try docTest(source, child, &w);
        }

        last_comment = null;
    }

    // Write output
    const out_path = "doc.md";
    try platform.fs.cwd().writeFile(.{ .sub_path = out_path, .data = output.items });
    // platform.debug.print("Generated {s} ({d} bytes)\n", .{ out_path, output.items.len });
}

fn docFn(source: []const u8, node: ts.TSNode, w: anytype, comment: ?[]const u8) anyerror!void {
    const name = getFieldText(source, node, "name") orelse "anonymous";
    try w.writeAll("### `fn ");
    try w.writeAll(name);

    // Params
    const count = ts.ts_node_child_count(node);
    var i: u32 = 0;
    while (i < count) : (i += 1) {
        const child = ts.ts_node_child(node, i);
        const ct = span(ts.ts_node_type(child));
        if (std.mem.eql(u8, ct, "params")) {
            try w.writeAll("(");
            try docParams(source, child, w);
            try w.writeAll(")");
        } else if (std.mem.eql(u8, ct, "->")) {
            try w.writeAll(" -> ");
        } else if (std.mem.eql(u8, ct, "prim_type")) {
            try w.writeAll(nodeText(source, child));
        }
    }
    try w.writeAll("`\n\n");

    if (comment) |c_text| {
        try w.writeAll(stripComment(c_text));
        try w.writeAll("\n\n");
    }
}

fn docStruct(source: []const u8, node: ts.TSNode, w: anytype, comment: ?[]const u8) anyerror!void {
    const name = getFieldText(source, node, "name") orelse "Struct";
    try w.writeAll("### struct ");
    try w.writeAll(name);
    try w.writeAll("\n\n");

    if (comment) |c_text| {
        try w.writeAll(stripComment(c_text));
        try w.writeAll("\n\n");
    }

    try w.writeAll("| Field | Type |\n|---|---|\n");
    const count = ts.ts_node_child_count(node);
    var i: u32 = 0;
    while (i < count) : (i += 1) {
        const child = ts.ts_node_child(node, i);
        const ct = span(ts.ts_node_type(child));
        if (std.mem.eql(u8, ct, "identifier")) {
            try w.writeAll("| `");
            try w.writeAll(nodeText(source, child));
            try w.writeAll("` | ");
            var j: u32 = i + 1;
            while (j < count) : (j += 1) {
                const next = ts.ts_node_child(node, j);
                if (std.mem.eql(u8, span(ts.ts_node_type(next)), "prim_type")) {
                    try w.writeAll("`");
                    try w.writeAll(nodeText(source, next));
                    try w.writeAll("`");
                    i = j;
                    break;
                }
            }
            try w.writeAll(" |\n");
        }
    }
    try w.writeAll("\n");
}

fn docEnum(source: []const u8, node: ts.TSNode, w: anytype, comment: ?[]const u8) anyerror!void {
    const name = getFieldText(source, node, "name") orelse "Enum";
    try w.writeAll("### enum ");
    try w.writeAll(name);
    try w.writeAll("\n\n");

    if (comment) |c_text| {
        try w.writeAll(stripComment(c_text));
        try w.writeAll("\n\n");
    }

    try w.writeAll("Variants: ");
    const count = ts.ts_node_child_count(node);
    var first = true;
    var i: u32 = 0;
    while (i < count) : (i += 1) {
        const child = ts.ts_node_child(node, i);
        if (std.mem.eql(u8, span(ts.ts_node_type(child)), "type_name")) {
            const txt = nodeText(source, child);
            if (!std.mem.eql(u8, txt, name)) {
                if (!first) try w.writeAll(", ");
                first = false;
                try w.writeAll("`");
                try w.writeAll(txt);
                try w.writeAll("`");
            }
        }
    }
    try w.writeAll("\n\n");
}

fn docEffect(source: []const u8, node: ts.TSNode, w: anytype, comment: ?[]const u8) anyerror!void {
    var name: []const u8 = "Effect";
    const count = ts.ts_node_child_count(node);
    var i: u32 = 0;
    while (i < count) : (i += 1) {
        const child = ts.ts_node_child(node, i);
        if (std.mem.eql(u8, span(ts.ts_node_type(child)), "type_name")) {
            name = nodeText(source, child);
            break;
        }
    }

    try w.writeAll("### `effect ");
    try w.writeAll(name);
    try w.writeAll("`\n\n");

    if (comment) |c_text| {
        try w.writeAll(stripComment(c_text));
        try w.writeAll("\n\n");
    }

    try w.writeAll("Operations:\n");
    i = 0;
    while (i < count) : (i += 1) {
        const child = ts.ts_node_child(node, i);
        if (std.mem.eql(u8, span(ts.ts_node_type(child)), "fn_sig")) {
            try w.writeAll("- `");
            try w.writeAll(nodeText(source, child));
            try w.writeAll("`\n");
        }
    }
    try w.writeAll("\n");
}

fn docNamed(source: []const u8, node: ts.TSNode, w: anytype, kind: []const u8, comment: ?[]const u8) anyerror!void {
    const name = getFieldText(source, node, "name") orelse kind;
    try w.writeAll("### ");
    try w.writeAll(kind);
    try w.writeAll(" ");
    try w.writeAll(name);
    try w.writeAll("\n\n");
    if (comment) |c_text| {
        try w.writeAll(stripComment(c_text));
        try w.writeAll("\n\n");
    }
}

fn docTest(source: []const u8, node: ts.TSNode, w: anytype) anyerror!void {
    const name = getFieldText(source, node, "name") orelse "test";
    try w.writeAll("- Test: ");
    try w.writeAll(name);
    try w.writeAll("\n");
}

fn docParams(source: []const u8, node: ts.TSNode, w: anytype) anyerror!void {
    const count = ts.ts_node_child_count(node);
    var first = true;
    var i: u32 = 0;
    while (i < count) : (i += 1) {
        const child = ts.ts_node_child(node, i);
        if (std.mem.eql(u8, span(ts.ts_node_type(child)), "param")) {
            if (!first) try w.writeAll(", ");
            first = false;
            try w.writeAll(nodeText(source, child));
        }
    }
}

fn stripComment(text: []const u8) []const u8 {
    if (text.len >= 3 and text[0] == '-' and text[1] == '-') {
        const rest = text[2..];
        if (rest.len > 0 and rest[0] == ' ') return rest[1..];
        return rest;
    }
    return text;
}

fn span(ptr: [*c]const u8) []const u8 {
    return std.mem.span(ptr);
}

fn nodeText(source: []const u8, node: ts.TSNode) []const u8 {
    const s = ts.ts_node_start_byte(node);
    const e = ts.ts_node_end_byte(node);
    return source[s..e];
}

fn getFieldText(source: []const u8, node: ts.TSNode, field: []const u8) ?[]const u8 {
    const child = ts.ts_node_child_by_field_name(node, field.ptr, @intCast(field.len));
    if (ts.ts_node_is_null(child)) return null;
    return nodeText(source, child);
}
